name: Generate Snake Game

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        uses: actions/checkout@v2

      - name: Generate Snake Game
        uses: Platane/snk@v3.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
